### ISSUE TITLE
The file "merges.txt" couldn't be opened because there is no such file

### ISSUE THREAD

**Issue by pgib** [justjake/Gauss#3]
I managed to get this built and running (thank you!) but any time I try to generate a image, I get this error:

```
The file "merges.txt" couldn't be opened because there is no such file.
```

<img width="491" alt="image" src="https://user-images.githubusercontent.com/13967/209882169-37b9b010-3842-409c-8b28-234472f1b796.png">

**Comment by TanujW** [comment]
@pgib I had the same issue.

Rename the "Resources" folder to the model name (e.g., sd1.5) and make sure your Xcode path for sd1.5 points to the renamed resources folder.

So your merges.txt file should be in a folder that looks like:

`Gauss/compiled-models/sd1.5/sd1.5/merges.txt`
